Dev
over-geek/Recipe-app pull request #27
Opened 2023-10-20 21:36 UTC by over-geek

## Recipe App: Final Changes

In this milestone, these were the features implemented:
- A login page.
- A registration page.
- A food list (with all CRUD implementation, except for 'update').
- A recipes list (with all CRUD implementation, except for 'update').
- A general shopping list view (all missing food for all your recipes and total price).
- A list of all public recipes from other users with their names and total prices.

collaborators: @francksefu @over-geek

2023-10-20 22:53 UTC, Strangeal requested changes
Hi @over-geek and @francksefu, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![](https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExMjBkMDI3OWJlYzRhNWVlNmIyZmE5NjU5NzFlZTA0NDVjZWFhMmQ2NSZlcD12MV9pbnRlcm5hbF9naWZzX2dpZklkJmN0PWc/UdaSUYClr92cjWpeVx/giphy.gif)

## Highlights
- Good **PR** title ✅ 
- Descriptive *PR* description ✅ 
- Implement the features ✅ 
- Nice *UI* design ✅ 
- Professional `README` template ✅ 
- Correct `GitHub` workflow ✅ 
- Meaningful **Github** commits ✅ 
- Correct `.github/workflows` for linters ✅ 
- Followed *best-practices* ✅ 
- Well structured project ✅ 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-10-20 22:53 UTC, Strangeal commented on app/views/recipes/show.html.erb
> +          </button>
- [ ] Great job on your capstone project's UI. it's truly impressive! 😊 However, there's a small adjustment I'd recommend to ensure that your design aligns with the wireframe provided in the project requirements.

   - When examining your recipe details page, you'll notice that the button used to switch a recipe between `public` and `private` doesn't match the wireframe's design. In the wireframe, the button is a toggle, more like a switch, but in your current design, it's not. I'd suggest considering this change, as using a toggle button would make it more intuitive for users to understand that they can switch between making a recipe `public` and `private`. 🔄🔒 See below for more details:
   
<table>
<tr>
<th align=“middle”>Wireframe</th>
<th align=“middle”>Your design</th>
</tr>
<tr>
<td>
<img width="1140" src="https://github.com/over-geek/Recipe-app/assets/107192076/2be8b18e-7c98-46c2-a1c3-7e90e8991ccb">
</td>
<td>
<img width="1440" alt="Screenshot 2023-10-20 at 22 15 10" src="https://github.com/over-geek/Recipe-app/assets/107192076/75df2fea-a2f6-4f72-8812-8b81a751c5c0">
</td>
</tr>
</table>

This adjustment should not only enhance the visual consistency with the project requirements but also improve the overall user experience. 

Happy coding! 😊👨‍💻🚀

2023-10-20 22:53 UTC, Strangeal commented on app/views/recipes/public_recipes.html.erb
> +<% end %>
- [ ] Great job on creating such an engaging and visually appealing UI for your public recipe page! 👏 However, I noticed that your current design deviates from the wireframe provided in the project requirements. To ensure your design aligns with the wireframe and project specifications, I recommend making some adjustments. See below for more details on design differences:

<table>
<tr>
<th align=“middle”>Original design</th>
<th align=“middle”>Your design</th>
</tr>
<tr>
<td>
<img width="1140" src="https://github.com/over-geek/Recipe-app/assets/107192076/61d7b8aa-7fb5-47c7-bdc4-7b68eaced9d1">
</td>
<td>
<img width="1440" alt="Screenshot 2023-10-20 at 22 22 17" src="https://github.com/over-geek/Recipe-app/assets/107192076/d4cf8de3-9c77-4b8f-a425-71e34b0c152d">
</td>
</tr>
</table>

Aligning your design with the wireframe not only ensures consistency but also demonstrates your keen attention to detail. 🧐
Happy coding! 😊👨‍💻🚀

2023-10-20 22:53 UTC, Strangeal commented on app/controllers/foods_controller.rb
> +end
- [ ] Excellent work in defining your controller action methods! 👍 However, I recommend marking the highlighted methods as `private` level methods. This practice enhances the encapsulation of your code and ensures that these methods are not accessible from outside the class. 

Happy coding! 😊👏

2023-10-21 09:31 UTC, shella12 approved these changes
Hi @over-geek and @francksefu, 


## Status : APPROVED 🥳 🥳 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

<img src="https://media0.giphy.com/media/3kuSo744UIPJjcJUEn/giphy.gif"/>

## Highlights

- Made required methods private ✔️ 
- Added toggle button for public recipes ✔️ 
- Implemented all requirements 👏 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-11-03 12:34 UTC, merged